name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest .
        flake8 --max-line-length=150 .

    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ env.NOW }}
        path: |
          /home/runner/work/hse-devops-CI-CD/hse-devops-CI-CD
          !/home/runner/work/hse-devops-CI-CD/hse-devops-CI-CD/**/*.md

